#
# The MIT License (MIT)
#
# Copyright (c) 2018 Tyler Bucher
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

name: SdEconomy
version: 2.1.3
main: net.reallifegames.sdeconomy.SdEconomy
author: agent6262
depend: [Vault]

commands:
  setprice:
    description: Sets the price of an item
    permission: sdeconomy.command.setprice
    usage: /<command> [alias] [itemtype:data] [price]
  removeprice:
    description: Removes the price of an item
    permission: sdeconomy.command.removeprice
    usage: /<command> [alias]
  getprice:
    description: Gets the price of an item
    permission: sdeconomy.command.getprice
    usage: /<command> [itemname]
  checksell:
    description: Checks the sell price of an item
    permission: sdeconomy.command.checksell
    usage: /<command> [itemname] [ammount]
  checkbuy:
    description: Checks the buy price of an item
    permission: sdeconomy.command.checkbuy
    usage: /<command> [itemname] [ammount]
  sell:
    description: Sells an item to the server
    permission: sdeconomy.command.sell
    usage: /<command>
  buy:
    description: Buys an item from the server
    permission: sdeconomy.command.buy
    usage: /<command> [itemname] [ammount]
  transactions:
    description: Checks a users transactions
    permission: sdeconomy.command.transactions
    usage: /<command> [playername] [pagenumber]
  sdversion:
    description: Gets the current version of this plugin
    permission: sdeconomy.command.version
    usage: /<command>
  sditems:
    description: Opens an inventory listing all the items you can buy from the SdEconomy
    permission: sdeconomy.command.sditems
    usage: /<command>